Skinner-SAS-de-CV/Skinner-Frontend

- src/app/analyze/page.tsx
- src/app/register/RegisterJobForm.tsx
- src/app/register/page.tsx
- src/components/pageContainer.tsx
https://github.com/user-attachments/assets/3a1d5f16-10d3-4d55-aaef-e8d02097174b
> Usar un solo componente(PageContainer) para definir el layout

- src/components/navbar.tsx
> issue-10 remover el botón en las versiones moviles

- .env.local.sample
- .gitignore
- package-lock.json
- package.json
- src/app/analyze/ResumeAnalyzer.tsx
Ahora estamos tomando en cuenta el markdown del resultado de la IA(#1):
https://github.com/user-attachments/assets/ac1edd38-51e7-4616-99b3-4ded80872afd
> Adición de react-markdown para que el feedback de la IA se vea mejor

- src/app/analyze/ResumeAnalyzer.tsx
Cambios para resolver #13 
Esto aprendí hoy: https://tailwindcss.com/docs/hover-focus-and-other-states#file
Me está encantando aún má tailwind! Me avisás si está bien el botón ahora.
> issue-13: Adjustando estilo de Seleccionar Arquivo

- src/app/analyze/ResumeAnalyzer.tsx
- src/lib/api.ts
(https://github.com/Skinner-SAS-de-CV/Skinner-Frontend/issues/15) Es mejor usar el id para llamar el backend. Este cambio hace eso con clientes y trabajos
https://github.com/user-attachments/assets/f3d16eda-fc8d-4fe2-a4f0-d27027e6581e
> issue-15: usar id en vez de nombre para llamadas a backend

- src/app/about/page.tsx
- src/components/navbar.tsx
> cambio de color a letras en el about y agreagdo boton de contacto

- src/components/footer.tsx
https://github.com/Skinner-SAS-de-CV/issues/issues/4
También, actualicé el enlace e icono de X. https://github.com/lucide-icons/lucide/issues/670
> issue-4: agregar icono de email, usar svg de X

- src/app/about/AboutUs.tsx
- src/app/page.tsx
> modificando el texto de toda la web y boton de contacto en el about

- src/app/contact/Contacts.tsx
- src/app/contact/page.tsx
- src/lib/api.ts
ya hice el form y voy hacer merge para probarlo en produccion.
> agregando el endpoint a la api

- src/app/analyze/ResumeAnalyzer.tsx
- src/app/analyze/page.tsx
- src/app/register/RegisterJobForm.tsx
- src/app/register/page.tsx
- src/lib/api.ts
Esto solo es para cuando el frontend manda un currículo para revisar. Tendremos que hacer esto para las otras rutas, pero te queria mostrar como lo haria para ver si está bien.
También tenía una duda sobre por qué usamos `fetch` y también `axios`. Podriamos solo usar fetch.
Creo que hay que ver cómo podemos usar `auth` en vez del `useAuth()` hook. Me funcionó pero parece que pueda ser que nos de problemas en el futuro: https://clerk.com/docs/hooks/use-auth#how-to-use-the-use-auth-hook
> issue-6: enviar token para backend para que backend autorice acceso

- src/app/about/AboutUs.tsx
Acá pongo dos video que tienen unos problemas. Creo que los arreglé pero seria bueno tratar esto junto con vos cuando tengás tiempo. Creo que problema viene no solo del gradiante de color, sino también que cambiamos el tamaño del texto para que se vea mejor en pantallas más pequeñas.
https://github.com/user-attachments/assets/97cf807b-6cd4-4cca-83e6-27f673280bf7
https://github.com/user-attachments/assets/7e29e42b-2f4d-4d15-b5f7-d298f45538c0
También puse el cambio del enlace para pedir un demo, puedo quitar ese cambio si no lo querés.
> issue-27: modificar estilos para que la palabra talentos no desaparezca

- src/app/analyze/ResumeAnalyzer.tsx
> issue-24: modificar estilo de formulario

- src/app/about/AboutUs.tsx
he agreagado cards con motion.div  a la parte donde va mision y vision y objetivos etc... pero creo que al agregar las cards las letras de arriba donde dice: "TRANSFORMANDO LA ADQUICION DE TALENTOS" Se desconfiguraron esta separadas.
> modificando la secion de mision vision etc

- src/app/analyze/components/AnalyzeForm.tsx
- src/app/analyze/components/Result.tsx
> Issue 42 limpiar resultado

- package-lock.json
- package.json
- src/app/recruiter/search/buscador.tsx
- src/app/recruiter/search/components/PDFCard.tsx
- src/app/recruiter/search/page.tsx
- src/components/ui/accordion.tsx
- src/components/ui/table.tsx
- src/middleware.ts
- tailwind.config.ts
Bueno intente usar el GeneratePDF  logre que apareciera el botón de descarga al lado de cada candidato. Yo se que falta mas para construir, como por ejemplo en ese pdf que obtenga toda la  información del análisis que se hizo, también voy a adjuntar un error que me apareció ahí que no logre descifrarlo aun...
> construyendo el componente recruiter

- src/components/navbar.tsx
> agreagndi enlaces al navbar

- src/app/candidate/onboard/page.tsx
- src/lib/api/perfil.ts
- src/middleware.ts
también cambié la orden del middleware para resolver un problema con el onboard.
> issue-61: crear opción para conectar a nuevo backend para perfiles

- package-lock.json
- package.json
- src/app/recruiter/search/components/AnalisisDialog.tsx
- src/app/recruiter/search/components/AnalisisPDF.tsx
Ejemplo de CV:
[Curriculum Nestor Stanley Serrano Fuentes.pdf](https://github.com/user-attachments/files/20766907/Curriculum.Nestor.Stanley.Serrano.Fuentes.pdf)
> issue-69: usar windy-pdf para crear pdfs

- src/app/recruiter/search/components/AnalisisDialog.tsx
- src/app/recruiter/search/components/AnalisisPDF.tsx
> issue-67: justificar texto y usar la palabra calificación en vez de match score

- src/app/candidate/home/features.tsx
- src/app/candidate/onboard/page.tsx
- src/app/candidate/payment/page.tsx
> modificando la redireccion de analyze a payment

- src/app/candidate/analyze/components/AnalyzeForm.tsx
- src/lib/errors.ts
Esto no debería ser fusionado hasta que https://github.com/Skinner-SAS-de-CV/skinner/pull/6 este en producción.
> issue-62: habilitando ruta para hacer analisis usando el backend de nestjs

- src/app/recruiter/search/components/AnalisisCompareDialog.tsx
- src/app/recruiter/search/components/AnalisisDataTable.tsx
Como se ve la página:
Como se ve el diálogo abierto:
la información que usé para modificar el estilo del campo seleccionado: https://tailwindcss.com/docs/hover-focus-and-other-states#data-attributes
en ingles:
> Issue 70 estilos

- src/app/candidate/signin/[[...rest]]/page.tsx
- src/components/navbar.tsx
- src/middleware.ts
> issue-64: agregar botón y página para hacer login

- src/app/candidate/analyze/components/AnalyzeForm.tsx
- src/app/candidate/analyze/page.tsx
- src/components/ui/alert.tsx
- src/lib/api/candidato.ts
Ejemplo de como
https://github.com/user-attachments/assets/8d5968eb-c096-4625-86e5-635d050977fb
Los mensajes que aparecen
1 o menos intentos:
Más de un intento:
> issue-77: agregando mensaje de saldo restante

- src/app/recruiter/trabajos/JobsList.tsx
- src/app/recruiter/trabajos/components/JobsDataTable.tsx
- src/app/recruiter/trabajos/page.tsx
> pagina de mis trabajos
